# Generated by Django 4.2.3 on 2023-09-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=30)),
                ('othernames', models.CharField(max_length=30)),
                ('directorate', models.CharField(choices=[('S', 'SCIENCE'), ('E', 'ENGINEERING')], max_length=2)),
                ('department', models.CharField(choices=[('CSIT', 'COMPUTER SCIENCE'), ('MEC', 'MECHANICAL ENGINEERING'), ('PEG', 'PETROLEUM ENGINEERING AND GEOSCIENCE')], max_length=6)),
                ('program_of_study', models.CharField(choices=[('N', 'ND'), ('H', 'HND')], max_length=1)),
                ('study_mode', models.CharField(choices=[('P', 'PART-TIME'), ('F', 'FULL-TIME')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
