# Generated by Django 4.2.3 on 2023-09-05 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_rename_user_studentprofile_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='posted_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
