# Generated by Django 4.2.3 on 2023-09-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_testing_alter_studentprofile_posted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Petroleum Engineering', 'Petroleum Engineering')], max_length=25),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='directorate',
            field=models.CharField(choices=[('Science', 'Science'), ('Engineerin', 'Engineerin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='program_of_study',
            field=models.CharField(choices=[('ND', 'ND'), ('H', 'HND')], max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='study_mode',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=10),
        ),
    ]
