# Generated by Django 4.2.3 on 2023-09-05 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_delete_testing_alter_studentprofile_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Null', 'Null')], max_length=6)),
                ('age', models.IntegerField()),
                ('job_status', models.CharField(max_length=15)),
                ('office_number', models.CharField(max_length=30)),
                ('educational_position', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
