# Generated by Django 4.2.3 on 2023-09-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='user_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
