# Generated by Django 4.2.3 on 2023-09-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_dummyform_age_alter_dummyform_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyform',
            name='firstname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
