# Generated by Django 4.2.3 on 2023-09-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_dummyform_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyform',
            name='firstname',
            field=models.CharField(max_length=40),
        ),
    ]
