# Generated by Django 4.2.3 on 2023-09-06 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_alter_dummyform_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyform',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dummyform',
            name='student_affair_comment',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='dummyform',
            name='student_affair_reviev',
            field=models.CharField(blank=True, default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dummyform',
            name='lastname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dummyform',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Null', 'Null')], max_length=6, null=True),
        ),
    ]
