# Generated by Django 4.2.3 on 2023-09-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_dummyform_posted_by_dummyform_student_affair_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyform',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
