# Generated by Django 4.2.3 on 2023-09-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_dummyform_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyform',
            name='student_affair_reviev',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
    ]
