# Generated by Django 4.2.3 on 2023-09-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_dummyform_student_affair_reviev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyform',
            name='student_affair_reviev',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
