# Generated by Django 4.2.3 on 2023-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_student_affair_reviev_dummyform_student_affair_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyform',
            name='student_affair_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
    ]
