# Generated by Django 4.2.3 on 2023-09-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_dummyform_student_affair_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyform',
            name='sug_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='dummyform',
            name='sug_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dummyform',
            name='student_affair_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
