# Generated by Django 4.2.3 on 2023-09-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_dummyform_sug_comment_dummyform_sug_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyform',
            name='sug_review',
            field=models.CharField(blank=True, default='pending', max_length=15, null=True),
        ),
    ]
