# Generated by Django 4.2.3 on 2023-09-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_dummyform_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyform',
            name='firstname',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
