# Generated by Django 4.2.3 on 2023-09-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceform',
            name='alumini_receipt_num_date',
            field=models.DateField(verbose_name='Date issued(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='date_of_birth',
            field=models.DateField(verbose_name='DOB (mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='date_of_completion',
            field=models.DateField(verbose_name='Date of completion(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='enterpreneur_receipt_num_date',
            field=models.DateField(verbose_name='Date issued(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='mat_receipt_num_date',
            field=models.DateField(verbose_name='Date isued(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_1_date',
            field=models.DateField(verbose_name='Date issued(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_2_date',
            field=models.DateField(verbose_name='Date issued(mm/dd/year)'),
        ),
    ]
