# Generated by Django 4.2.3 on 2023-09-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_clearanceform_alumini_receipt_num_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceform',
            name='last_room_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Last room number'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='libary_registration_num',
            field=models.IntegerField(null=True, verbose_name='library registration number'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='alumini_receipt_num',
            field=models.IntegerField(verbose_name='Alumini receipt number'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='alumini_receipt_num_date',
            field=models.DateField(verbose_name='Date issued:(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='date_of_birth',
            field=models.DateField(verbose_name='DOB:(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='date_of_completion',
            field=models.DateField(verbose_name='Date of completion:(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='enterpreneur_receipt_num',
            field=models.IntegerField(verbose_name='Enterpreneur receipt number'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='enterpreneur_receipt_num_date',
            field=models.DateField(verbose_name='Date issued:(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='mat_receipt_num',
            field=models.IntegerField(verbose_name='Matriculation receipt number'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='mat_receipt_num_date',
            field=models.DateField(verbose_name='Date isued:(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_1',
            field=models.IntegerField(verbose_name='School fees (year-1) receipt number'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_1_date',
            field=models.DateField(verbose_name='Date issued:(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_2',
            field=models.IntegerField(verbose_name='School fees (year-2) receipt number'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_2_date',
            field=models.DateField(verbose_name='Date issued:(mm/dd/year)'),
        ),
    ]
