# Generated by Django 4.2.3 on 2023-09-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_clearanceform_last_room_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceform',
            name='chief_liberian_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='chief_liberian_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='csit_hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='csit_hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='csit_hod_review',
            field=models.CharField(blank=True, default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='liberian_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='peg_hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='peg_hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='peg_hod_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='sa_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='sport_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='sport_officer_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='sport_officer_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='student_affair_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='student_affair_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='student_union_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='student_union_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='sug_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='alumini_receipt_num_date',
            field=models.DateField(verbose_name='Date issued(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='date_of_completion',
            field=models.DateField(verbose_name='Date of completion(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='enterpreneur_receipt_num_date',
            field=models.DateField(verbose_name='Date issued(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='last_room_num',
            field=models.CharField(max_length=10, null=True, verbose_name='Last room number'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='mat_receipt_num_date',
            field=models.DateField(verbose_name='Date isued(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_1_date',
            field=models.DateField(verbose_name='Date issued(mm/dd/year)'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_2_date',
            field=models.DateField(verbose_name='Date issued(mm/dd/year)'),
        ),
    ]
