# Generated by Django 4.2.3 on 2023-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_clearanceform_chief_liberian_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceform',
            name='certificate_processing_fee_receipt',
            field=models.IntegerField(null=True, verbose_name='Enterpreneur receipt NO'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='certificate_processing_fee_receipt_date',
            field=models.DateField(null=True, verbose_name='Date issued '),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='convocation_gown_receipt_num',
            field=models.IntegerField(null=True, verbose_name='Convocation gown receipt NO'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='convocation_gown_receipt_num_date',
            field=models.IntegerField(null=True, verbose_name='Date issued'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='program_of_study',
            field=models.CharField(choices=[('ND', 'ND'), ('HND', 'HND')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Null', 'Null')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='alumini_receipt_num',
            field=models.IntegerField(verbose_name='Alumini receipt NO'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='alumini_receipt_num_date',
            field=models.DateField(verbose_name='Date issued '),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='date_of_birth',
            field=models.DateField(verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='date_of_completion',
            field=models.DateField(verbose_name='Date of completion '),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='enterpreneur_receipt_num',
            field=models.IntegerField(verbose_name='Enterpreneur receipt NO'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='enterpreneur_receipt_num_date',
            field=models.DateField(verbose_name='Date issued '),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='last_room_num',
            field=models.CharField(max_length=10, null=True, verbose_name='Last room NO'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='libary_registration_num',
            field=models.IntegerField(null=True, verbose_name='library registration NO'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='mat_receipt_num',
            field=models.IntegerField(verbose_name='Matriculation receipt NO'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='mat_receipt_num_date',
            field=models.DateField(null=True, verbose_name='Date isued '),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_1',
            field=models.IntegerField(verbose_name='School fees (year-1) receipt NO'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_1_date',
            field=models.DateField(verbose_name='Date issued '),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_2',
            field=models.IntegerField(verbose_name='School fees (year-2) receipt NO'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='school_fees_receipt_year_2_date',
            field=models.DateField(verbose_name='Date issued '),
        ),
    ]
