# Generated by Django 4.2.3 on 2023-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_clearanceform_certificate_processing_fee_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceform',
            name='convocation_gown_receipt_num_date',
            field=models.DateField(null=True, verbose_name='Date issued '),
        ),
    ]
