# Generated by Django 4.2.3 on 2023-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_clearanceform_convocation_gown_receipt_num_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceform',
            name='Student_affair_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='last_room_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Last room NO'),
        ),
    ]
