# Generated by Django 4.2.3 on 2023-09-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_clearanceform_student_affair_approval_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearanceform',
            old_name='Student_affair_approval_date',
            new_name='chief_liberian_approval_date',
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='boys_hostel_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='boys_hostel_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='boys_hostel_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='csit_hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='eed_hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='eed_hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='eed_hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='eed_hod_review',
            field=models.CharField(blank=True, default='null', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='iset_hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='iset_hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='iset_hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='iset_hod_review',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='mect_hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='mect_hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='mect_hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='mect_hod_review',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='mpre_hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='mpre_hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='mpre_hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='mpre_hod_review',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='nddc_hostel_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='nddc_hostel_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='nddc_hostel_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='nddc_hostel_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='noble_hostel_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='noble_hostel_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='noble_hostel_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='noble_hostel_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='peg_hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='pmbs_hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='pmbs_hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='pmbs_hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='pmbs_hod_review',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='pngpd_hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='pngpd_hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='pngpd_hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='pngpd_hod_review',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='ptdf_wing_a_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='ptdf_wing_a_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='ptdf_wing_a_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='ptdf_wing_a_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='ptdf_wing_b_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='ptdf_wing_b_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='ptdf_wing_b_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='ptdf_wing_b_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='slt_hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='slt_hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='slt_hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='slt_hod_review',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='sport_officer_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='student_affair_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='student_union_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='woet_hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='woet_hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='woet_hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='woet_hod_review',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='csit_hod_review',
            field=models.CharField(blank=True, default='null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Industrial Safety and Environmental', 'Industrial Safety and Environmental'), ('Mineral and Petroleum Resources', 'Mineral and Petroleum Resources'), ('Petroleum and Natural Gas', 'Petroleum and Natural Gas'), ('Petroleum Engineering and Geoscience', 'Petroleum Engineering and Geoscience'), ('Petroleum Marketing and Business Studies', 'Petroleum Marketing and Business Studies'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Welding and Fabrication', 'Welding and Fabrication')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='peg_hod_review',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Industrial Safety and Environmental', 'Industrial Safety and Environmental'), ('Mineral and Petroleum Resources', 'Mineral and Petroleum Resources'), ('Petroleum and Natural Gas', 'Petroleum and Natural Gas'), ('Petroleum Engineering and Geoscience', 'Petroleum Engineering and Geoscience'), ('Petroleum Marketing and Business Studies', 'Petroleum Marketing and Business Studies'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Welding and Fabrication', 'Welding and Fabrication')], max_length=50),
        ),
    ]
