# Generated by Django 4.2.3 on 2023-09-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_student_union_approval_date_clearanceform_sug_approval_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state_of_origin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='department',
            field=models.CharField(choices=[('Computer Science and Information Technology', 'Computer Science and Information Technology'), ('Mechanical Engineering Technology', 'Mechanical Engineering Technology'), ('Electrical Engineering', 'Electrical Engineering'), ('Industrial Safety', 'Industrial Safety'), ('Environmentl Technology', 'Environmentl Technology'), ('Mineral and Petroleum Resources', 'Mineral and Petroleum Resources'), ('Petroleum and Natural Gas Processing Technology', 'Petroleum and Natural Gas Processing Technology'), ('Petroleum Engineering and Geoscience', 'Petroleum Engineering and Geoscience'), ('Petroleum Marketing and Business Studies', 'Petroleum Marketing and Business Studies'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Welding Engineering and Offshore Technology', 'Welding Engineering and Offshore Technology'), ('Computer Engineering Technoloy', 'Computer Engineering Technoloy'), ('Mechatronics', 'Mechatronics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='dummyform',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('Computer Science and Information Technology', 'Computer Science and Information Technology'), ('Mechanical Engineering Technology', 'Mechanical Engineering Technology'), ('Electrical Engineering', 'Electrical Engineering'), ('Industrial Safety', 'Industrial Safety'), ('Environmentl Technology', 'Environmentl Technology'), ('Mineral and Petroleum Resources', 'Mineral and Petroleum Resources'), ('Petroleum and Natural Gas Processing Technology', 'Petroleum and Natural Gas Processing Technology'), ('Petroleum Engineering and Geoscience', 'Petroleum Engineering and Geoscience'), ('Petroleum Marketing and Business Studies', 'Petroleum Marketing and Business Studies'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Welding Engineering and Offshore Technology', 'Welding Engineering and Offshore Technology'), ('Computer Engineering Technoloy', 'Computer Engineering Technoloy'), ('Mechatronics', 'Mechatronics')], max_length=50),
        ),
    ]
