# Generated by Django 4.2.3 on 2023-09-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_studentprofile_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceform',
            name='boys_hostel_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='csit_hod_review',
            field=models.CharField(blank=True, default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='eed_hod_review',
            field=models.CharField(blank=True, default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='iset_hod_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='mect_hod_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='mpre_hod_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='nddc_hostel_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='noble_hostel_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='peg_hod_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='pmbs_hod_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='pngpd_hod_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='ptdf_wing_a_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='ptdf_wing_b_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='slt_hod_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='woet_hod_review',
            field=models.CharField(default='pending', max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='DummyForm',
        ),
    ]
