# Generated by Django 4.2.3 on 2023-09-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_clearanceform_boys_hostel_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceform',
            name='date_posted',
            field=models.DateField(null=True, verbose_name='Date posted '),
        ),
    ]
