# Generated by Django 4.2.3 on 2023-09-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_clearanceform_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceform',
            name='date_posted',
            field=models.DateField(auto_now_add=True, verbose_name='Date posted '),
        ),
    ]
