# Generated by Django 4.2.3 on 2023-09-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_clearanceform_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='state_of_origin',
            field=models.CharField(choices=[('D', 'Delta'), ('E', 'Edo')], max_length=50),
        ),
    ]
