# Generated by Django 4.2.3 on 2023-09-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='id_card',
            field=models.ImageField(null=True, upload_to='id-img', verbose_name='ID card'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_file',
            field=models.FileField(null=True, upload_to='student-file/', verbose_name='Student documents'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile-pics/', verbose_name='Passport photo'),
        ),
    ]
