# Generated by Django 4.2.3 on 2023-09-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_studentprofile_id_card_studentprofile_student_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile-pics/'),
        ),
    ]
