# Generated by Django 4.2.3 on 2023-09-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_studentaffairreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(default='pending', max_length=15)),
                ('comment', models.TextField(verbose_name='comment')),
                ('approved_by', models.CharField(max_length=50)),
                ('approval_date', models.DateField(verbose_name='Date of approval')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.clearanceform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
