# Generated by Django 4.2.3 on 2023-09-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_studentunion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentunion',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentAffairReview',
        ),
        migrations.DeleteModel(
            name='StudentUnion',
        ),
    ]
