# Generated by Django 4.2.3 on 2023-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_studentunion_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceform',
            name='hod_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of approval'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='hod_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='hod_comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='hod_review',
            field=models.CharField(blank=True, default='pending', max_length=15, null=True),
        ),
    ]
